services:
    xaben.instagram.service.instagrambridge:
        class: Xaben\InstagramBundle\Service\InstagramBridge
        arguments: [ @doctrine_cache.providers.ciofilm_json_cache, @logger, %xaben.instagram.config% ]

    xaben.instagram.block.instagram:
        class: Xaben\InstagramBundle\Block\InstagramBlock
        arguments: [ "xaben.instagram.block.instagram", @templating, @xaben.instagram.service.instagrambridge ]
        tags:
            - { name: sonata.block }