services:
    xaben.instagram.service.instagrambridge:
        class: Xaben\InstagramBundle\Service\InstagramBridge
        arguments: [ @=service(parameter('xaben.instagram.cache_service')), @logger, %xaben.instagram.config% ]

    xaben.instagram.block.instagram:
        class: Xaben\InstagramBundle\Block\InstagramBlock
        arguments: [ "xaben.instagram.block.instagram", @templating, @xaben.instagram.service.instagrambridge, %xaben.instagram.config% ]
        tags:
            - { name: sonata.block }